config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'remove_from_cart' => 'cart#remove_from_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'edit_line_item' => 'cart#edit_line_item'

  resources :orders
  resources :line_items
  devise_for :users
  root 'storefront#all_items'

  get 'by_category' => 'storefront#items_by_category'

  get 'by_brand' => 'storefront#items_by_brand'

  resources :products

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_filter :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
  	product = Product.find(params[:product_id])
  	if product.quantity < params[:qty].to_i
  		redirect_to product, notice: "Not enough quantity in stock."
  	else

    	line_item = LineItem.new
    	line_item.product_id = params[:product_id].to_i
    	line_item.quantity = params[:qty]

    if user_signed_in?
      line_item.customer_key = current_user.id
    else
      line_item.customer_key = remote_ip
    end 

  	line_item.save

  	line_item.line_item_total = line_item.quantity * line_item.product.price
  	line_item.save 

  	redirect_to view_order_path

  	end 
  end

  def remove_from_cart
    LineItem.find(params[:id]).destroy

    redirect_to view_order_path
  end

  def edit_line_item
    line_item = LineItem.find(params[:id])

    if Product.find(line_item.product_id).quantity < params[:qty].to_i
      redirect_to view_order_path, notice: "Not enough quantity in stock." 
    else
      line_item.quantity = params[:qty].to_i
      line_item.save
      redirect_to view_order_path
    end
  end

  def view_order
    if user_signed_in? 
  	 @line_items = LineItem.where(customer_key: current_user.id.to_s)
    else
      @line_items = LineItem.where(customer_key: remote_ip)
    end
  end

  def checkout
  	@line_items = LineItem.all
  	@order = Order.new
  	@order.user_id = current_user.id

  	sum = 0

  	@line_items.each do |line_item|
  		@order.order_items[line_item.product_id] = line_item.quantity
  		sum += line_item.line_item_total
  	end

  	@order.subtotal = sum
  	@order.sales_tax = sum * 0.07
  	@order.grand_total = @order.subtotal + @order.sales_tax
  	@order.save

  	@line_items.each do |line_item|
  		line_item.product.quantity -= line_item.quantity
  		line_item.product.save
  	end

  	@line_items.destroy_all
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thank you for shopping with us!</h1>
<p>Please review your order:</p>

<div>
	<% @order.order_items.each do |k,v| %>
		<ul>
			<li><%= Product.find(k).name %> - <%= v %></li>
		</ul>
	<% end %>

	<p>
		Subtotal: <%= number_to_currency @order.subtotal %>
	</p>
	<p>
		Sales Tax: + <%= number_to_currency @order.sales_tax %>
	</p>	
	<p>
	         -----------
	</p>
	<p>
		Grand Total: <%= number_to_currency @order.grand_total %>
	</p>
</div>

<div>
	<%= form_tag order_complete_path do %>
		<article>
			<label class="amount">
				<span><%= number_to_currency @order.grand_total %></span>
			</label>
		</article>
		<div>
			<%= hidden_field_tag :order_id, @order.id %>
		</div>

		<script src="http://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order #<%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<h5>
	Order #<%= @order.id %> will be shipping to you, <%= @order.user.name %>, as soon as possible.
</h5>

app/views/cart/view_order.html.erb
<h1>My Cart</h1>

<div class="row">
	<% if @line_items.empty? %>
		<h3> There's nothing here yet. </h3>
	<% else %>
		<% @line_items.each do |line_item| %>
			<ul>
				<!-- name of product -->
				<li><%= line_item.product.name %></li>
				<!-- price of each product -->
				<li><%= number_to_currency line_item.product.price %>/ea.</li>
				<!-- amount of product -->
				<div id="current-quantity-<%= line_item.id %>">
					<li>Qty: <%= line_item.quantity %></li>
				</div> 

				<p id="notice"><%= notice %></p>

				<div id="change-quantity-<%= line_item.id %>" class="invisible">
					<%= form_tag(edit_line_item_path, class: "inline-form") do %>
						<%= number_field_tag :quantity, line_item.quantity %>
						<%= hidden_field_tag :id, line_item.id %>
						<%= submit_tag "Change Quantity", class: "btn btn-sm btn-warning" %> 
					<% end %>
				</div>
				<!-- subtotal -->
				<li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>

				<p>
					<a href="#" id="edit_qty_<%= line_item.id %>"> Edit Quantity</a> 
				</p>


				<li><%= link_to "Remove from Cart", remove_from_cart_path(id: line_item.id) %></li>
			</ul>
			<script>
				$(document).ready(function(){
					$('edit_qty_<%= line_item.id %>').click(function(){
						$('#current-quantity)-<%= line_item.id %>').addClass('invisible');
						$('#change-quantity)-<%= line_item.id %>').removeClass('invisible');
					});
				});
			</script>
		<% end %> 
	<% end %> 
</div>

<div>
	<p><%= link_to "Continue Shopping", root_path, class: "btn btn-info" %></p>
	<p><%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-success" %></p>
</div>