config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'remove_from_cart' => 'cart#remove_from_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'edit_line_item' => 'cart#edit_line_item'

  resources :orders
  resources :line_items
  devise_for :users
  root 'storefront#all_items'

  get 'by_category' => 'storefront#items_by_category'

  get 'by_brand' => 'storefront#items_by_brand'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :catergory_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.text_field :name, placeholder: "Product Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :price, placeholder: "Price", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.number_field :quantity, placeholder: "Quantity", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.text_field :brand, placeholder: "Brand", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:catergory_id, @categories.collect {|c| [c.name, c.id]}, {include_blank: "Please Select a Category"}) %>
  </div>
  <div class="form-group">
    <strong>Upload Product Image: </strong>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_notallowed.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 center-it">
		<h3>Access is restricted.</h3>
		<p><%= image_tag "notallowed.gif" %></p>
		<p><%= link_to "Back to Shopping", root_path %></p>

	</div>
</div>

app/views/products/_tocart.html.erb
<% if @product.quantity > 0 %>
<p>
  <%= form_tag(add_to_cart_path) do %>
    <%= number_field_tag :quantity, nil, min: 1, placeholder: "How Many?" %>
    <%= hidden_field_tag :product_id, @product.id %>
    <%= submit_tag "Add to Cart", class: "btn btn-success" %>
  <% end %>
</p>
<% end %>

app/views/products/edit.html.erb
<% if can? :update, @product %>

	<h1>Editing Product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
	
<% else %>
  <%= render 'notallowed' %>
<% end %>

app/views/products/index.html.erb
<% if can? :update, @product %>

<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.catergory_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
<% else %>
  <%= render 'notallowed' %>

<% end %>

app/views/products/new.html.erb
<% if can? :update, @product %>

<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

<% else %>
  <%= render 'notallowed' %>

<% end %>

app/views/products/show.html.erb
<p><%= image_tag @product.image.url(:medium) %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<% if @product.quantity <= 5 && @product.quantity >= 1 %>
<p>
  Order now! Only <%= @product.quantity %> left in stock! 
</p>
<% elsif @product.quantity == 0 %>
<p>
  This item is no longer in stock.
</p>
<% end %>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.catergory_id %>
</p>

<% if notice != nil %>
  <p id="notice" class="alert alert-danger"><%= notice %></p>
<% end %> 

<% if @product.quantity > 0 %>
<p>
  <%= form_tag(add_to_cart_path) do %>
    <%= number_field_tag :quantity, nil, min: 1, placeholder: "How Many?" %>
    <%= hidden_field_tag :product_id, @product.id %>
    <%= submit_tag "Add to Cart", class: "btn btn-success" %>
  <% end %>
</p>
<% end %>

<% if can? :update, @product %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
<% end %> 